---
- hosts: all
  become: true
  tasks:

  - name: install aptitude
    apt:
      name: "aptitude"
      state: latest
      update_cache: "yes"


  - name: apt upgrade
    apt:
      name: "*"
      state: latest
      update_cache: "yes"
